import { EntityMap, EntityMapOne, Predicate, Update } from "@ngrx/entity";
import { createAction, props } from "@ngrx/store";
import { MarketCategory } from "../../store.model";

export const loadMarketCategories = createAction('[MarketCategory/API] Load MarketCategories', props<{ marketCategories: MarketCategory[] }>());
export const loadMarketCategoriesSuccess = createAction('[MarketCategory/API] Load MarketCategories', props<{ data: MarketCategory[] }>());
export const loadMarketCategoriesFailure = createAction('[MarketCategory/API] Load MarketCategories', props<{ error: Error }>());
export const setMarketCategories = createAction('[MarketCategory/API] Set MarketCategories', props<{ marketCategories: MarketCategory[] }>());
export const addMarketCategory = createAction('[MarketCategory/API] Add MarketCategory', props<{ marketCategory: MarketCategory }>());
export const setMarketCategory = createAction('[MarketCategory/API] Set MarketCategory', props<{ marketCategory: MarketCategory }>());
export const upsertMarketCategory = createAction('[MarketCategory/API] Upsert MarketCategory', props<{ marketCategory: MarketCategory }>());
export const addMarketCategories = createAction('[MarketCategory/API] Add MarketCategories', props<{ marketCategories: MarketCategory[] }>());
export const upsertMarketCategories = createAction('[MarketCategory/API] Upsert MarketCategories', props<{ marketCategories: MarketCategory[] }>());
export const updateMarketCategory = createAction('[MarketCategory/API] Update MarketCategory', props<{ update: Update<MarketCategory> }>());
export const updateMarketCategories = createAction('[MarketCategory/API] Update MarketCategories', props<{ updates: Update<MarketCategory>[] }>());
export const mapMarketCategory = createAction('[MarketCategory/API] Map MarketCategory', props<{ entityMap: EntityMapOne<MarketCategory> }>());
export const mapMarketCategories = createAction('[MarketCategory/API] Map MarketCategories', props<{ entityMap: EntityMap<MarketCategory> }>());
export const deleteMarketCategory = createAction('[MarketCategory/API] Delete MarketCategory', props<{ id: string }>());
export const deleteMarketCategories = createAction('[MarketCategory/API] Delete MarketCategories', props<{ ids: string[] }>());
export const deleteMarketCategoriesByPredicate = createAction('[MarketCategory/API] Delete MarketCategories By Predicate', props<{ predicate: Predicate<MarketCategory> }>());
export const clearMarketCategories = createAction('[MarketCategory/API] Clear MarketCategories');